apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-access-policy
spec:
  podSelector:
    matchLabels:
      component: kube-apiserver
  ingress:
    - from:
      - ipBlock:
          cidr: 192.168.0.0/24 # Replace with the desired IP range
