apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: juice-shop
  name: deployment-juice-shop
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-juice-shop
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-juice-shop
    spec:
      containers:
      - image: bkimminich/juice-shop
        imagePullPolicy: Always
        name: app-juice-shop
        ports:
        - containerPort: 3000
