apiVersion: v1
kind: Service
metadata:
  namespace: juice-shop
  name: service-juice-shop
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-juice-shop
